default_install_hook_types: [pre-commit, pre-push]
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10  # if you update this, also update pyproject.toml
    hooks:
      - name: Ruff formatting
        id: ruff-format
        entry: bash -c 'ruff format --force-exclude "$@"; git add -u' --
      - name: Ruff linting
        id: ruff
        stages: [pre-push]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.2
    hooks:
      - id: sqlfluff-lint
        types: []
        types_or: [sql,jinja]
