repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - name: Ruff formatting
        id: ruff-format
      - name: Ruff linting
        id: ruff
        stages: [pre-push]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.4
    hooks:
      - id: sqlfluff-lint