# This study is used as an example (but realistic) workflow a user can follow to see how NLP data
# flows through the Cumulus pipeline.

study_prefix = "example_nlp"

[[stages.nlp]]
description = "NLP"
files = [
    "nlp.workflow",
]
type = "build:serial"

[[stages.ranges]]
description = "Range calculation"
files = [
    "calculate_ranges.py",
]
type = "build:serial"
