import os
from unittest import mock

from cumulus_library import StudyManifest
from cumulus_library.builders.valueset import umls, valueset_utils


@mock.patch.dict(
    os.environ,
    clear=True,
)
def test_umls_lookup(mock_db_config_rxnorm):
    cursor = mock_db_config_rxnorm.db.cursor()
    manifest = StudyManifest()
    manifest._study_config = {"study_prefix": "test"}
    mock_db_config_rxnorm.options = {"umls_stewards": "medrt"}
    valueset_config = valueset_utils.ValuesetConfig(
        umls_stewards={"medrt": {"sab": "MED-RT", "search_terms": ["Opioid"]}}
    )
    umls.generate_umls_tables(mock_db_config_rxnorm, manifest, valueset_config)

    res = cursor.execute("SELECT * FROM test__umls_valuesets_rels").fetchall()
    expected = {
        (
            "medrt",
            1,
            "C2917209",
            "C2917209",
            "RN",
            "isa",
            "C0006491",
            "MSHFRE",
            "PT",
            "N0000175686",
            "Competitive Opioid Antagonists",
        ),
        (
            "medrt",
            1,
            "C2917209",
            "C2917209",
            "RN",
            "isa",
            "C0006491",
            "MSH",
            "PT",
            "N0000175686",
            "Competitive Opioid Antagonists",
        ),
        (
            "medrt",
            1,
            "C2917209",
            "C2917209",
            "CHD",
            None,
            "C0006405",
            "CSP",
            "PT",
            "N0000175686",
            "Competitive Opioid Antagonists",
        ),
        (
            "medrt",
            1,
            "C2917209",
            "C2917209",
            "RN",
            "isa",
            "C0006405",
            "MSH",
            "PT",
            "N0000175686",
            "Competitive Opioid Antagonists",
        ),
        (
            "medrt",
            2,
            "C0006405",
            "C2917209",
            "RN",
            "isa",
            "C0006405",
            "MSH",
            "MH",
            "D002047",
            "Buprenorphine",
        ),
        (
            "medrt",
            2,
            "C0006405",
            "C2917209",
            "CHD",
            None,
            "C0006405",
            "MSH",
            "MH",
            "D002047",
            "Buprenorphine",
        ),
        (
            "medrt",
            2,
            "C0006491",
            "C2917209",
            "RN",
            "isa",
            "C0006491",
            "MSH",
            "MH",
            "D002077",
            "Butorphanol",
        ),
        (
            "medrt",
            2,
            "C0006405",
            "C2917209",
            "CHD",
            None,
            "C0006405",
            "CSP",
            "PT",
            "0092-7100",
            "buprenorphine",
        ),
        (
            "medrt",
            2,
            "C0006491",
            "C2917209",
            "RN",
            "isa",
            "C0006491",
            "MSHFRE",
            "MH",
            "D002077",
            "Butorphanol",
        ),
        (
            "medrt",
            2,
            "C0006405",
            "C2917209",
            "RN",
            "isa",
            "C0006405",
            "CSP",
            "PT",
            "0092-7100",
            "buprenorphine",
        ),
        (
            "medrt",
            3,
            "C1169989",
            "C0006405",
            "RO",
            "has_part",
            "C1169989",
            "SNOMEDCT_US",
            "PT",
            "425741009",
            "Buprenorphine- and naloxone-containing product",
        ),
        (
            "medrt",
            3,
            "C3205902",
            "C0006491",
            "CHD",
            "isa",
            "C3205902",
            "RXNORM",
            "SCDG",
            "1151379",
            "butorphanol Injectable Product",
        ),
        (
            "medrt",
            3,
            "C1169989",
            "C0006405",
            "CHD",
            "isa",
            "C1169989",
            "SNOMEDCT_US",
            "PT",
            "425741009",
            "Buprenorphine- and naloxone-containing product",
        ),
        (
            "medrt",
            3,
            "C1169989",
            "C0006405",
            "RO",
            "has_part",
            "C1169989",
            "RXNORM",
            "MIN",
            "352364",
            "buprenorphine / naloxone",
        ),
        (
            "medrt",
            3,
            "C3205902",
            "C0006491",
            "RO",
            "has_ingredient",
            "C3205902",
            "RXNORM",
            "SCDG",
            "1151379",
            "butorphanol Injectable Product",
        ),
        (
            "medrt",
            3,
            "C3205902",
            "C0006491",
            "CHD",
            "isa",
            "C3205902",
            "SNOMEDCT_US",
            "PT",
            "430388001",
            "Butorphanol-containing product in parenteral dose form",
        ),
        (
            "medrt",
            3,
            "C3205902",
            "C0006491",
            "RO",
            "has_ingredient",
            "C3205902",
            "SNOMEDCT_US",
            "PT",
            "430388001",
            "Butorphanol-containing product in parenteral dose form",
        ),
        (
            "medrt",
            3,
            "C1169989",
            "C0006405",
            "CHD",
            "isa",
            "C1169989",
            "RXNORM",
            "MIN",
            "352364",
            "buprenorphine / naloxone",
        ),
        (
            "medrt",
            4,
            "C4755717",
            "C3205902",
            "CHD",
            "isa",
            "C4755717",
            "SNOMEDCT_US",
            "PT",
            "778584004",
            "Butorphanol only product in parenteral dose form",
        ),
        (
            "medrt",
            4,
            "C0774321",
            "C3205902",
            "RN",
            "isa",
            "C0774321",
            "SNOMEDCT_US",
            "PT",
            "785210007",
            "Butorphanol tartrate 1 mg/mL solution for injection",
        ),
    }

    assert set(res) == expected

    res = cursor.execute("SELECT * FROM test__umls_valuesets").fetchall()
    expected = {
        (
            886627,
            "medrt",
            4,
            "C0774321",
            "C3205902",
            "RN",
            "isa",
            "C0774321",
            "SNOMEDCT_US",
            "PT",
            "785210007",
            "Butorphanol tartrate 1 mg/mL solution for injection",
        ),
        (
            352364,
            "medrt",
            3,
            "C1169989",
            "C0006405",
            "CHD",
            "isa",
            "C1169989",
            "RXNORM",
            "MIN",
            "352364",
            "buprenorphine / naloxone",
        ),
        (
            352364,
            "medrt",
            3,
            "C1169989",
            "C0006405",
            "RO",
            "has_part",
            "C1169989",
            "RXNORM",
            "MIN",
            "352364",
            "buprenorphine / naloxone",
        ),
    }
    assert set(res) == expected
