-- noqa: disable=all
/*
This is a reference output of the SQL generated by builder_core_medication.py 
that is used by the core__encounter_type table. It is not invoked directly.
*/

CREATE TABLE core__medication AS (
    WITH
    
    mcc_nonnull AS (
        SELECT 
            id,
            encounter, 
            subject, 
            medicationcodeableconcept 
        FROM medicationrequest 
        WHERE medicationcodeableconcept IS NOT NULL
        AND encounter IS NOT NULL
    ),
    inline_medication AS (
        SELECT
            id,
            subject.reference as "patient_id",
            encounter.reference AS "encounter_id",
            t.r.code,
            t.r.display,
            t.r.system AS code_system,
            t.r.userselected
        FROM mcc_nonnull,
        unnest(medicationcodeableconcept.coding) AS t(r)
    ),
    
    mrc_med_ref AS (
        SELECT medicationreference
        FROM medicationrequest
        WHERE
            medicationreference IS NOT NULL
            AND medicationcodeableconcept IS NULL
    ),

    mrc_ref_id AS (
        SELECT DISTINCT substring(mrc_med_ref.medicationreference.reference, 2) AS id
        FROM mrc_med_ref
        WHERE
            medicationreference.reference IS NOT NULL
            AND medicationreference.reference LIKE '#%'
    ),

    mrc_contained_nested AS (
        SELECT
            id,
            encounter,
            subject,
            contained
        FROM medicationrequest
        WHERE contained IS NOT NULL
    ),

    mrc_contained_unnest AS (
        SELECT DISTINCT
            cn.id AS mr_id,
            cn.encounter,
            cn.subject,
            row.id,
            row.code
        FROM mrc_contained_nested AS cn,
            unnest(cn.contained) AS t (row)
    ),

    contained_medication AS (
        SELECT
            cu.mr_id AS id,
            cu.encounter.reference AS encounter_id,
            cu.subject.reference AS patient_id,
            'None' AS code,
            cu.code.text AS display,
            'None' AS code_system,
            false AS userselected
        FROM mrc_contained_unnest AS cu
        INNER JOIN mrc_ref_id AS ri ON ri.id = cu.id
    ),
    
    mre_med_ref AS (
        SELECT
            mr.id,
            mr.encounter,
            mr.subject,
            mr.medicationreference
        FROM medicationrequest AS mr
        WHERE mr.medicationreference IS NOT NULL
    ),

    mre_ref_id AS (
        SELECT DISTINCT
            mr.id,
            mr.encounter,
            mr.subject,
            substring(mr.medicationreference.reference, 12) AS id
        FROM mre_med_ref AS mr
        WHERE
            mr.reference IS NOT NULL
            AND mr.reference LIKE 'Medication/%'
    ),

    external_medications AS (
        SELECT DISTINCT
            m.id,
            m.encounter AS encounter_id,
            m.subject AS patient_id,
            t.r.code AS code,
            t.r.display AS display,
            t.r.system AS code_system,
            t.r.userselected AS userselected
        FROM medication AS m,
            unnest(code) AS t (r)
        INNER JOIN mre_ref_id AS ri ON ri.id = m.id
    )
    
    SELECT
        id,
        encounter_id,
        patient_id,
        code,
        display,
        code_system,
        userselected
    FROM
        inline_medication
    UNION
    
    SELECT
        id,
        encounter_id,
        patient_id,
        code,
        display,
        code_system,
        userselected
    FROM
        contained_medication
    UNION
    
    SELECT
        id,
        encounter_id,
        patient_id,
        code,
        display,
        code_system,
        userselected
    FROM
        external_medications
);
