-- noqa: disable=all
-- This sql was autogenerated as a reference example using the library
-- CLI. Its format is tied to the specific database it was run against,
-- and it may not be correct for all databases. Use the CLI's build 
-- option to derive the best SQL for your dataset.

-- ###########################################################

DROP table IF EXISTS discovery__tmp_allergyintolerance_clinicalstatus;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_allergyintolerance_code;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_allergyintolerance_reaction_exposureroute;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_allergyintolerance_reaction_manifestation;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_allergyintolerance_reaction_substance;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_allergyintolerance_verificationstatus;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_condition_category;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_condition_code;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_diagnosticreport_category;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_diagnosticreport_code;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_diagnosticreport_conclusioncode;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_documentreference_category;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_documentreference_type;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_encounter_class;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_encounter_hospitalization_dischargedisposition;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_encounter_priority;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_encounter_reasoncode;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_encounter_servicetype;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_encounter_type;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_location_type;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_medicationrequest_medicationcodeableconcept;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_medication_codecodeableconcept;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_medication_medicationcode;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_observation_category;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_observation_code;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_observation_component_code;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_observation_dataabsentreason;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_observation_interpretation;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_observation_valuecodeableconcept;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_organization_type;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_patient_maritalstatus;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_practitionerrole_code;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_practitionerrole_specialty;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_practitioner_qualification_code;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_procedure_bodysite;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_procedure_category;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_procedure_code;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_procedure_complication;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_procedure_focaldevice_action;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_procedure_followup;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_procedure_outcome;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_procedure_performer_function;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_procedure_reasoncode;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_procedure_statusreason;

-- ###########################################################

DROP table IF EXISTS discovery__tmp_procedure_usedcode;
