study_prefix = "discovery"

[[stages.build_discovery]]
label= "code detection"
files = [
    "code_detection.py",
]
type="build:parallel"
[[stages.build_discovery]]
label = "code union"
files= [
    "code_union.py"
]
type="build:parallel"
[[stages.build_discovery]]
label = "temp data cleanup"
files = [
    "cleanup_tmp.py"
]
type="build:parallel"


[[stages.build_discovery]]
tables = [
    "discovery__code_sources",
]
type = "export:counts"