# 'study_prefix' should be a string at the start of each table. We'll use this
# to clean up queries, so it should be unique. Name your tables in the following
# format: [study_prefix]__[table_name]. It should probably, but not necessarily,
# be the same name as the folder the study definition is in.
study_prefix = "template"

# For most use cases, this should not be required, but if you need to programmatically
# build tables, you can provide a list of files implementing BaseTableBuilder.
# See vocab and core studies for examples of this pattern. These run before
# any SQL execution
# [table_builder_config]
# file_names = [
#     "my_table_builder.py",
# ]

# The following section describes all tables that should be generated directly
# from SQL files.
[sql_config]
# 'file_names' defines a list of sql files to execute, in order, in this folder.
# Recommended order: Any ancillary config (like a list of condition codes),
# tables/view selecting subsets of data from FHIR data, tables/views creating 
# summary statistics.
file_names = [
    "setup.sql",
    "lab_observations.sql",
    "counts.sql",
    "date_range.sql"
]


# The following section defines parameters related to exporting study data from
# your athena database
[export_config]
# The following tables will be output to disk when an export is run. In most cases,
# only count tables should be output in this way.
export_list = [
    "template__count_influenza_test_month",
]

# For generating counts table in a more standardized manner, we have a class in the 
# main library you can extend that will handle most of the logic of assembling 
# queries for you. We use this pattern for generating the core tables, as well
# other studies authored inside BCH. These will always be run after any other
# SQL queries have been generated
# [counts_builder_config]
# file_names = [
#    "count.py"
# ]

# For more specialized statistics, we provide a toml-based config entrypoint. The
# details of these configs will vary, depending on which statistical method you're
# invoking. For more details, see the statistics section of the docs for a list of
# supported approaches.
# These will run last, so all the data in your study will exist by the time these
# are invoked.
# [statistics_config]
# file_names = 
# [
#    "psm_config.toml"
# ]
