-- noqa: disable=all
-- This sql was autogenerated as a reference example using the library
-- CLI. Its format is tied to the specific database it was run against,
-- and it may not be correct for all databases. Use the CLI's build 
-- option to derive the best SQL for your dataset.

-- ###########################################################

CREATE TABLE core__observation_dn_category AS (
    WITH

    system_category_0 AS (
        SELECT DISTINCT
            s.id AS id,
            u.codeable_concept.code,
            u.codeable_concept.display,
            u.codeable_concept.system AS code_system
        FROM
        
           observation AS s,
            UNNEST(s.category) AS cc (cc_row),
            UNNEST(cc.cc_row.coding) AS u (codeable_concept)
    ), --noqa: LT07

    union_table AS (
        SELECT
            id,
            code_system,
            code,
            display
        FROM system_category_0
        
    )
    SELECT
        id,
        code,
        code_system,
        display
    FROM union_table
);


-- ###########################################################

CREATE TABLE core__observation_dn_code AS (
    WITH

    system_code_0 AS (
        SELECT DISTINCT
            s.id AS id,
            u.codeable_concept.code,
            u.codeable_concept.display,
            u.codeable_concept.system AS code_system
        FROM
        
           observation AS s,
            UNNEST(s.code.coding) AS u (codeable_concept)
    ), --noqa: LT07

    union_table AS (
        SELECT
            id,
            code_system,
            code,
            display
        FROM system_code_0
        
    )
    SELECT
        id,
        code,
        code_system,
        display
    FROM union_table
);


-- ###########################################################

CREATE TABLE IF NOT EXISTS "main"."core__observation_dn_interpretation"
AS (
    SELECT * FROM (
        VALUES
        (cast(NULL AS varchar),cast(NULL AS varchar),cast(NULL AS varchar),cast(NULL AS varchar))
    )
        AS t ("id","code","code_system","display")
);

-- ###########################################################

CREATE TABLE core__observation_dn_valuecodeableconcept AS (
    WITH

    system_valuecodeableconcept_0 AS (
        SELECT DISTINCT
            s.id AS id,
            u.codeable_concept.code,
            u.codeable_concept.display,
            u.codeable_concept.system AS code_system
        FROM
        
           observation AS s,
            UNNEST(s.valuecodeableconcept.coding) AS u (codeable_concept)
    ), --noqa: LT07

    union_table AS (
        SELECT
            id,
            code_system,
            code,
            display
        FROM system_valuecodeableconcept_0
        
    )
    SELECT
        id,
        code,
        code_system,
        display
    FROM union_table
);


-- ###########################################################

CREATE TABLE IF NOT EXISTS "main"."core__observation_dn_dataabsentreason"
AS (
    SELECT * FROM (
        VALUES
        (cast(NULL AS varchar),cast(NULL AS varchar),cast(NULL AS varchar),cast(NULL AS varchar))
    )
        AS t ("id","code","code_system","display")
);

-- ###########################################################



CREATE TABLE core__observation AS
WITH temp_observation AS (
    SELECT
        o.id,
        o.status,
        o.valuestring,
        o.valuequantity.value AS valuequantity_value,
        o.valuequantity.comparator AS valuequantity_comparator,
        o.valuequantity.unit AS valuequantity_unit,
        o.valuequantity.system AS valuequantity_system,
        o.valuequantity.code AS valuequantity_code,
        date_trunc('day', date(from_iso8601_timestamp(o."effectivedatetime")))
            AS effectivedatetime_day,
        date_trunc('week', date(from_iso8601_timestamp(o."effectivedatetime")))
            AS effectivedatetime_week,
        date_trunc('month', date(from_iso8601_timestamp(o."effectivedatetime")))
            AS effectivedatetime_month,
        date_trunc('year', date(from_iso8601_timestamp(o."effectivedatetime")))
            AS effectivedatetime_year,
        odc.code AS observation_code,
        odc.code_system AS observation_code_system,
        odcat.code AS category_code,
        odcat.code_system AS category_code_system,
        odi.code AS interpretation_code,
        odi.code_system AS interpretation_code_system,
        odi.display AS interpretation_display,
        odvcc.code AS valuecodeableconcept_code,
        odvcc.code_system AS valuecodeableconcept_code_system,
        odvcc.display AS valuecodeableconcept_display,
        odda.code AS dataabsentreason_code,
        odda.code_system AS dataabsentreason_code_system,
        odda.display AS dataabsentreason_display,
        o.referencerange,
        o.valuequantity,
        o.subject.reference AS subject_ref,
        o.encounter.reference AS encounter_ref
    FROM observation AS o
    LEFT JOIN core__observation_dn_category AS odcat ON o.id = odcat.id
    LEFT JOIN core__observation_dn_code AS odc ON o.id = odc.id
    LEFT JOIN core__observation_dn_interpretation AS odi ON o.id = odi.id
    LEFT JOIN core__observation_dn_valuecodeableconcept AS odvcc ON o.id = odvcc.id
    LEFT JOIN core__observation_dn_dataabsentreason AS odda ON o.id = odda.id
)

SELECT
    id,
    category_code,
    category_code_system,
    status,
    observation_code,
    observation_code_system,
    interpretation_code,
    interpretation_code_system,
    interpretation_display,
    effectivedatetime_day AS obs_date,
    effectivedatetime_week AS obs_week,
    effectivedatetime_month AS obs_month,
    effectivedatetime_year AS obs_year,
    valuecodeableconcept_code,
    valuecodeableconcept_code_system,
    valuecodeableconcept_display,
    valuequantity_value,
    valuequantity_comparator,
    valuequantity_unit,
    valuequantity_system,
    valuequantity_code,
    valuestring,
    dataabsentreason_code,
    dataabsentreason_code_system,
    dataabsentreason_display,
    subject_ref,
    encounter_ref,
    concat('Observation/', id) AS observation_ref
FROM temp_observation
WHERE
    effectivedatetime_day BETWEEN date(
        from_iso8601_timestamp('2016-06-01')
    ) AND current_date;
