-- noqa: disable=all
-- This sql was autogenerated as a reference example using the library
-- CLI. Its format is tied to the specific database it was run against,
-- and it may not be correct for all databases. Use the CLI's build 
-- option to derive the best SQL for your dataset.

-- ###########################################################




CREATE TABLE core__medicationrequest_dosageinstruction AS (
    SELECT
        'x' AS id,
        cast(NULL AS bigint) AS row,
        cast(NULL AS bigint) AS dosage_sequence,
        'x' AS dosage_text,
        'x' AS dosage_patient_instruction,
        cast(NULL AS boolean) AS dosage_as_needed_bool,
        'x' AS dosage_route_code,
        'x' AS dosage_route_system,
        'x' AS dosage_route_display,
        'x' AS dosage_route_text,
        'x' AS dosage_timing_text,
        cast(NULL AS bigint) AS dosage_timing_count,
        cast(NULL AS bigint) AS dosage_timing_count_max,
        cast(NULL AS double) AS dosage_timing_duration,
        cast(NULL AS double) AS dosage_timing_duration_max,
        cast(NULL AS varchar) AS dosage_timing_duration_unit,
        cast(NULL AS bigint) AS dosage_timing_frequency,
        cast(NULL AS bigint) AS dosage_timing_frequency_max,
        cast(NULL AS double) AS dosage_timing_period,
        cast(NULL AS double) AS dosage_timing_period_max,
        'x' AS dosage_timing_period_unit,
        cast(NULL AS bigint) AS dosage_timing_offset,
        cast(NULL AS date) AS dosage_timing_bounds_start,
        cast(NULL AS date) AS dosage_timing_bounds_end,
            cast(NULL AS varchar) AS dosage_dose_type,
            cast(NULL AS double) AS dosage_dose_value,
            cast(NULL AS double) AS dosage_dose_low_value,
            cast(NULL AS double) AS dosage_dose_high_value,
            cast(NULL AS varchar) AS dosage_dose_unit,
            cast(NULL AS varchar) AS dosage_dose_system,
            cast(NULL AS varchar) AS dosage_dose_code,
        cast(NULL AS timestamp) AS authoredOn,
        cast(NULL AS date) AS authoredOn_month,
        'x' AS medicationrequest_ref,
        'x' AS subject_ref,
        'x' AS encounter_ref
    WHERE 1 = 0 -- empty table
);
