-- noqa: disable=all
-- This sql was autogenerated as a reference example using the library
-- CLI. Its format is tied to the specific database it was run against,
-- and it may not be correct for all databases. Use the CLI's build 
-- option to derive the best SQL for your dataset.

-- ###########################################################

CREATE TABLE core__medicationdispense AS (
    WITH

    md_basics AS (
        SELECT DISTINCT
        md.id,
        md.status,
        md.context.reference AS encounter_ref,
        md.subject.reference AS subject_ref,
        md.medicationReference.reference AS med_ref,
        md.quantity.value AS quantity_value,
        md.quantity.unit AS quantity_unit,
        md.daysSupply.value AS days_supply_value,
        md.daysSupply.unit AS days_supply_unit,
        cast(from_iso8601_timestamp(md."whenPrepared") AS timestamp) AS whenPrepared,
        cast(from_iso8601_timestamp(md."whenHandedOver") AS timestamp) AS whenHandedOver,
        date_trunc('month', cast(from_iso8601_timestamp(md."whenPrepared") AS date))
            AS whenPrepared_month,
        date_trunc('day', cast(from_iso8601_timestamp(md."whenHandedOver") AS date))
            AS whenHandedOver_day,
        date_trunc('week', cast(from_iso8601_timestamp(md."whenHandedOver") AS date))
            AS whenHandedOver_week,
        date_trunc('month', cast(from_iso8601_timestamp(md."whenHandedOver") AS date))
            AS whenHandedOver_month,
        date_trunc('year', cast(from_iso8601_timestamp(md."whenHandedOver") AS date))
            AS whenHandedOver_year
        FROM medicationdispense AS md
        WHERE (md.status IS NULL OR md.status <> 'entered-in-error')
    ),

    contained_refs AS (
        SELECT DISTINCT
            md.id,
            substring(md.med_ref, 2) AS medication_id
        FROM md_basics AS md
        WHERE md.med_ref IS NOT NULL AND REGEXP_LIKE(md.med_ref, '^#.*$')
    ),

    external_refs AS (
        SELECT DISTINCT
            md.id,
            substring(md.med_ref, 12) AS medication_id
        FROM md_basics AS md
        WHERE md.med_ref IS NOT NULL AND REGEXP_LIKE(md.med_ref, '^Medication/.*$')
    ),

    unified_codes AS (
        
        SELECT
            md.id,
            mdic.code AS medication_code,
            mdic.system AS medication_system,
            mdic.display AS medication_display
        FROM md_basics AS md
        INNER JOIN core__medicationdispense_dn_inline_code AS mdic ON md.id = mdic.id

        
        UNION
        SELECT
            md.id,
            mdcc.code AS medication_code,
            mdcc.system AS medication_system,
            mdcc.display AS medication_display
        FROM md_basics AS md
        INNER JOIN contained_refs AS cr ON md.id = cr.id
        INNER JOIN core__medicationdispense_dn_contained_code AS mdcc
            ON cr.id = mdcc.id AND cr.medication_id = mdcc.contained_id
        WHERE mdcc.resource_type = 'Medication'

        
        UNION
        SELECT
            md.id,
            mc.code AS medication_code,
            mc.system AS medication_system,
            mc.display AS medication_display
        FROM md_basics AS md
        INNER JOIN external_refs AS er ON md.id = er.id
        INNER JOIN core__medication_dn_code AS mc ON er.medication_id = mc.id
    )

    SELECT
        md.id,
        md.status,

        mdc.code AS category_code,
        mdc.system AS category_system,
        mdc.display AS category_display,

        mdt.code AS type_code,
        mdt.system AS type_system,
        mdt.display AS type_display,

        uc.medication_code,
        uc.medication_system,
        uc.medication_display,

        -- We ensure these are doubles, because nullable_cols() above will cast
        -- them as varchar if they aren't in the schema.
        cast(md.quantity_value AS double) AS quantity_value,
        md.quantity_unit,
        cast(md.days_supply_value AS double) AS days_supply_value,
        md.days_supply_unit,

        md.whenPrepared,
        md.whenPrepared_month,
        md.whenHandedOver,
        md.whenHandedOver_day,
        md.whenHandedOver_week,
        md.whenHandedOver_month,
        md.whenHandedOver_year,

        concat('MedicationDispense/', md.id) AS medicationdispense_ref,
        md.subject_ref,
        md.encounter_ref
    FROM md_basics AS md
    LEFT JOIN unified_codes AS uc ON md.id = uc.id
    LEFT JOIN core__medicationdispense_dn_category AS mdc ON md.id = mdc.id
    LEFT JOIN core__medicationdispense_dn_type AS mdt ON md.id = mdt.id
);

-- ###########################################################



-- This table includes authorizing MedicationRequests so we do not drastically
-- increase core__medicationdispense. A single dispense may have multiple authorizing
-- requests. Skip this table if there is no authorizingPrescription.

CREATE TABLE core__medicationdispense_authorizingprescription AS (
    WITH

    flattened_rows AS (
        WITH
        data_and_row_num AS (
            SELECT
                t.id AS id,
                generate_subscripts(t."authorizingPrescription", 1) AS row,
                UNNEST(t."authorizingPrescription") AS data -- must unnest in SELECT here
            FROM medicationdispense AS t
        )
        SELECT
            id,
            row,
            data."reference"
        FROM data_and_row_num
    )

    SELECT
        f.id,
        f.row,
        f.reference AS medicationrequest_ref
    FROM flattened_rows AS f
    WHERE f.reference IS NOT NULL
);
