-- noqa: disable=all
-- This sql was autogenerated as a reference example using the library CLI.
-- Its format is tied to the specific database it was run against, and it may not
-- be correct for all databases. Use the CLI's build option to derive the best SQL
-- for your dataset.

-- ###########################################################

CREATE TABLE core__documentreference_dn_type AS (
    WITH

    system_type_0 AS (
        SELECT DISTINCT
            s.id AS id,
            u.codeable_concept.code AS code,
            u.codeable_concept.display AS display,
            u.codeable_concept.system AS code_system
        FROM
            documentreference AS s,
            UNNEST(s.type.coding) AS u (codeable_concept)
    ), --noqa: LT07

    union_table AS (
        SELECT
            id,
            code_system,
            code,
            display
        FROM system_type_0
    )
    SELECT
        id,
        code,
        code_system,
        display
    FROM union_table
);


-- ###########################################################


-- noqa: PRS
CREATE TABLE core__documentreference AS
WITH temp_documentreference AS (
    SELECT DISTINCT
        dr.id,
        dr.type,
        dr.status,
        dr.docstatus,
        dr.context,
        dr.subject.reference AS subject_ref,
        dr.context.period.start AS author_date,
        date_trunc('day', date(from_iso8601_timestamp(dr.context.period.start))) 
            AS author_day,
        date_trunc('week', date(from_iso8601_timestamp(dr.context.period.start))) 
            AS author_week,
        date_trunc('month', date(from_iso8601_timestamp(dr.context.period.start))) 
            AS author_month,
        date_trunc('year', date(from_iso8601_timestamp(dr.context.period.start))) 
            AS author_year,
        cdrt.code,
        cdrt.code_system,
        cdrt.display
    FROM documentreference AS dr
    LEFT JOIN core__documentreference_dn_type AS cdrt ON dr.id = cdrt.id
)

SELECT DISTINCT
    tdr.id,
    tdr.code AS doc_type_code,
    tdr.code_system AS doc_type_code_system,
    tdr.display AS doc_type_display,
    tdr.status,
    tdr.docstatus,
    context_encounter.encounter.reference AS encounter_ref,
    tdr.author_day AS author_date,
    tdr.author_week,
    tdr.author_month,
    tdr.author_year,
    tdr.subject_ref,
    concat('DocumentReference/', tdr.id) AS doc_ref
FROM temp_documentreference AS tdr,
    unnest(context.encounter) AS context_encounter (encounter) --noqa
WHERE date(tdr.author_day) BETWEEN date('2016-06-01') AND current_date;
