-- noqa: disable=all
-- This sql was autogenerated as a reference example using the library
-- CLI. Its format is tied to the specific database it was run against,
-- and it may not be correct for all databases. Use the CLI's build 
-- option to derive the best SQL for your dataset.

-- ###########################################################




CREATE TABLE core__medicationrequest_dosageinstruction AS (
    WITH
    parent AS (
        SELECT DISTINCT
            mr.id,
            mr.medicationrequest_ref,
            mr.subject_ref,
            mr.encounter_ref,
            mr.authoredOn,
            mr.authoredOn_month
        FROM core__medicationrequest AS mr
    ),

    dosage_rows AS (
        WITH
        data_and_row_num AS (
            SELECT
                t.id AS id,
                generate_subscripts(t."dosageInstruction", 1) AS row,
                UNNEST(t."dosageInstruction") AS "dosageInstruction" -- must unnest in SELECT here
            FROM medicationrequest AS t
        )
        SELECT
            id,
            row,
            "dosageInstruction"
        FROM data_and_row_num
    ),

    dosage_cols AS (
        SELECT
            d.id,
            d.row,
            cast(d.dosageInstruction.sequence AS bigint) AS dosage_sequence,
            d.dosageInstruction.text AS dosage_text,
            d.dosageInstruction.patientInstruction AS dosage_patient_instruction,
            cast(d.dosageInstruction.asNeededBoolean AS boolean) AS dosage_as_needed_bool,
            cast(NULL AS varchar) AS dosage_route_text,
            cast(NULL AS varchar) AS dosage_timing_text,
            cast(d.dosageInstruction.timing.repeat.frequency AS bigint)
                AS dosage_timing_frequency,
            cast(d.dosageInstruction.timing.repeat.period AS double) AS dosage_timing_period,
            d.dosageInstruction.timing.repeat.periodUnit AS dosage_timing_period_unit,
            cast(NULL AS date) AS dosage_timing_bounds_start,
            cast(NULL AS date) AS dosage_timing_bounds_end
        FROM dosage_rows AS d
    ),
    dose_rows AS (
        SELECT DISTINCT
            d.id,
            d.row,
            CASE
                WHEN u.dose_and_rate.doseQuantity.value IS NOT NULL
                    THEN 'quantity'
            END AS dosage_dose_type,
            cast(u.dose_and_rate.doseQuantity.value AS double) AS dosage_dose_value,
            cast(NULL AS double) AS dosage_dose_low_value,
            cast(NULL AS double) AS dosage_dose_high_value,
            cast(NULL AS varchar) AS dosage_dose_unit,
            cast(NULL AS varchar) AS dosage_dose_system,
            cast(NULL AS varchar) AS dosage_dose_code
        FROM
            dosage_rows AS d,
            unnest(d.dosageInstruction.doseAndRate) AS u (dose_and_rate) --noqa
    )

    SELECT
        dc.id,
        dc.row,

        dc.dosage_sequence,
        dc.dosage_text,
        dc.dosage_patient_instruction,
        dc.dosage_as_needed_bool,

        dr.code AS dosage_route_code,
        dr.system AS dosage_route_system,
        dr.display AS dosage_route_display,
        dc.dosage_route_text,

        dc.dosage_timing_text,
        dc.dosage_timing_frequency,
        dc.dosage_timing_period,
        dc.dosage_timing_period_unit,
        dc.dosage_timing_bounds_start,
        dc.dosage_timing_bounds_end,
        dq.dosage_dose_type,
        dq.dosage_dose_value,
        dq.dosage_dose_low_value,
        dq.dosage_dose_high_value,
        dq.dosage_dose_unit,
        dq.dosage_dose_system,
        dq.dosage_dose_code,

        p.authoredOn,
        p.authoredOn_month,

        p.medicationrequest_ref,
        p.subject_ref,
        p.encounter_ref
    FROM dosage_cols AS dc
    INNER JOIN parent AS p ON dc.id = p.id
    LEFT JOIN dose_rows AS dq ON dc.id = dq.id AND dc.row = dq.row
    LEFT JOIN core__medicationrequest_dn_dosage_route AS dr
        ON dc.id = dr.id AND dc.row = dr.row
);
