services:

  gpt-oss-120b:
    # Needs 80GB of GPU memory. A g6.12xlarge EC2 instance should work.
    # Docs: https://recipes.vllm.ai/openai/gpt-oss-120b
    image: vllm/vllm-openai:v0.10.2
    environment:
      - VLLM_ATTENTION_BACKEND=TRITON_ATTN_VLLM_V1  # needed for NVIDIA A10 and A100 chips
    command:
      - --download-dir=/data
      - --port=8086
      - --model=openai/gpt-oss-120b
      - --revision=b5c939de8f754692c1647ca79fbf85e8c1e70f8a
      - --tensor-parallel-size=4
    shm_size: 32G
    healthcheck:
      test: ["CMD", "wget", "localhost:8086/health", "--output-document=/dev/null"]
      start_period: 40m  # give plenty of time for startup, loading is slow
    volumes:
      - vllm-data:/data
    ports:
      - 8086:8086
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  llama4-scout:  # WIP, have not gotten it to run successfully yet
    # Needs 80GB of GPU memory. A g6.12xlarge EC2 instance should work.
    # Docs: https://recipes.vllm.ai/meta-llama/Llama-4-Scout-17B-16E-Instruct
    image: vllm/vllm-openai:v0.11.0
    environment:
      - HF_TOKEN
      - HUGGING_FACE_HUB_TOKEN
    command:
      - --download-dir=/data
      - --port=8087
      - --model=nvidia/Llama-4-Scout-17B-16E-Instruct-NVFP4
      - --revision=9417590c9bc99b359f3ac66d1346ecd54249888e
      - --tensor-parallel-size=4
    shm_size: 32G
    healthcheck:
      test: ["CMD", "wget", "localhost:8087/health", "--output-document=/dev/null"]
      start_period: 40m  # give plenty of time for startup, loading is slow
    volumes:
      - vllm-data:/data
    ports:
      - 8087:8087
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  vllm-data:
